/*
  Warnings:

  - You are about to drop the column `voicelink` on the `UserCredentials` table. All the data in the column will be lost.

*/
BEGIN TRY

BEGIN TRAN;

-- AlterTable
ALTER TABLE [dbo].[UserCredentials] ALTER COLUMN [_SALT] VARCHAR(3) NULL;
ALTER TABLE [dbo].[UserCredentials] ALTER COLUMN [cometname] VARCHAR(125) NULL;
ALTER TABLE [dbo].[UserCredentials] ALTER COLUMN [_TELECOM] VARCHAR(30) NULL;
ALTER TABLE [dbo].[UserCredentials] ALTER COLUMN [_BIRTHDATE] VARCHAR(100) NULL;
ALTER TABLE [dbo].[UserCredentials] ALTER COLUMN [_CIVILSTATUS] VARCHAR(100) NULL;
ALTER TABLE [dbo].[UserCredentials] ALTER COLUMN [_AGE] VARCHAR(2) NULL;
ALTER TABLE [dbo].[UserCredentials] ALTER COLUMN [_CITY] VARCHAR(100) NULL;
ALTER TABLE [dbo].[UserCredentials] ALTER COLUMN [_AREA] VARCHAR(100) NULL;
ALTER TABLE [dbo].[UserCredentials] ALTER COLUMN [_PROVINCE] VARCHAR(100) NULL;
ALTER TABLE [dbo].[UserCredentials] ALTER COLUMN [_COUNTRY] VARCHAR(100) NULL;
ALTER TABLE [dbo].[UserCredentials] ALTER COLUMN [_LEVEL] INT NULL;
ALTER TABLE [dbo].[UserCredentials] ALTER COLUMN [_SECONDLEVEL] INT NULL;
ALTER TABLE [dbo].[UserCredentials] ALTER COLUMN [_GROUPE] VARCHAR(50) NULL;
ALTER TABLE [dbo].[UserCredentials] ALTER COLUMN [_REGDATE] VARCHAR(100) NULL;
ALTER TABLE [dbo].[UserCredentials] ALTER COLUMN [_LOGGED] INT NULL;
ALTER TABLE [dbo].[UserCredentials] ALTER COLUMN [LASTLOGIN] VARCHAR(50) NULL;
ALTER TABLE [dbo].[UserCredentials] ALTER COLUMN [LASTLOGOUT] VARCHAR(50) NULL;
ALTER TABLE [dbo].[UserCredentials] ALTER COLUMN [_LASTACTIVITY] INT NULL;
ALTER TABLE [dbo].[UserCredentials] ALTER COLUMN [_USESMS] INT NULL;
ALTER TABLE [dbo].[UserCredentials] ALTER COLUMN [_SESSION] VARCHAR(100) NULL;
ALTER TABLE [dbo].[UserCredentials] ALTER COLUMN [_SESSIONDATA] VARCHAR(255) NULL;
ALTER TABLE [dbo].[UserCredentials] ALTER COLUMN [_DELETED] VARCHAR(1) NULL;
ALTER TABLE [dbo].[UserCredentials] ALTER COLUMN [_ACTIVATION] VARCHAR(255) NULL;
ALTER TABLE [dbo].[UserCredentials] ALTER COLUMN [sync] INT NULL;
ALTER TABLE [dbo].[UserCredentials] DROP COLUMN [voicelink];

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
