BEGIN TRY

BEGIN TRAN;

-- CreateTable
CREATE TABLE [dbo].[UserCredentials] (
    [id] INT NOT NULL IDENTITY(1,1),
    [username] VARCHAR(30) NOT NULL,
    [_PASSWORD] VARCHAR(64) NOT NULL,
    [_SALT] VARCHAR(3) NOT NULL,
    [voicelink] VARCHAR(125) NOT NULL,
    [avatar] TEXT,
    [firstname] VARCHAR(100) NOT NULL,
    [lastname] VARCHAR(100) NOT NULL,
    [cometname] VARCHAR(125) NOT NULL,
    [email] VARCHAR(100) NOT NULL,
    [_ADDRESS] VARCHAR(255) NOT NULL,
    [_TELECOM] VARCHAR(30) NOT NULL,
    [mobile] VARCHAR(100) NOT NULL,
    [_BIRTHDATE] VARCHAR(100) NOT NULL,
    [_CIVILSTATUS] VARCHAR(100) NOT NULL,
    [_AGE] VARCHAR(2) NOT NULL,
    [_CITY] VARCHAR(100) NOT NULL,
    [_AREA] VARCHAR(100) NOT NULL,
    [_PROVINCE] VARCHAR(100) NOT NULL,
    [_COUNTRY] VARCHAR(100) NOT NULL,
    [_LEVEL] INT NOT NULL,
    [_SECONDLEVEL] INT NOT NULL,
    [_GROUPE] VARCHAR(50) NOT NULL,
    [branch] TEXT,
    [_REGDATE] VARCHAR(100) NOT NULL,
    [_LOGGED] INT NOT NULL,
    [LASTLOGIN] VARCHAR(50) NOT NULL,
    [LASTLOGOUT] VARCHAR(50) NOT NULL,
    [_LASTACTIVITY] INT NOT NULL,
    [_USESMS] INT NOT NULL,
    [_SESSION] VARCHAR(100) NOT NULL,
    [_SESSIONDATA] VARCHAR(255) NOT NULL,
    [_DELETED] VARCHAR(1) NOT NULL,
    [_ACTIVATION] VARCHAR(255) NOT NULL,
    [sync] INT NOT NULL,
    [USER_ID_NUMBER] VARCHAR(60) NOT NULL,
    CONSTRAINT [UserCredentials_pkey] PRIMARY KEY CLUSTERED ([id])
);

-- CreateTable
CREATE TABLE [dbo].[Token] (
    [id] INT NOT NULL IDENTITY(1,1),
    [token] NVARCHAR(1000) NOT NULL,
    [userId] INT NOT NULL,
    [expirationTime] DATETIME2 NOT NULL,
    CONSTRAINT [Token_pkey] PRIMARY KEY CLUSTERED ([id]),
    CONSTRAINT [Token_token_key] UNIQUE NONCLUSTERED ([token])
);

-- CreateIndex
CREATE NONCLUSTERED INDEX [Token_userId_idx] ON [dbo].[Token]([userId]);

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
